### ISSUE TITLE
Test failures on 32 bit x86.

### ISSUE THREAD

**Issue by richardcochran** [mlichvar/linuxptp-testsuite#8] opened 2018-07-06 07:10 UTC
When running on 32 bit x86, the following two tests fail consistently.
```
  FAILED 2    (13-delayedfup 22-passiveport)
```
On 64 bit x86 those two tests both pass.

**Comment by mlichvar** [comment] 2018-07-09 09:08
Are there any error messages in `tmp/log*` ? Did it start with a recent change in clknetsim?

I cannot reproduce it. FWIW, the Fedora linuxptp package builds on i686:
https://kojipkgs.fedoraproject.org//packages/linuxptp/1.9.2/1.fc28/data/logs/i686/build.log

**Comment by mlichvar** [comment] 2020-08-12 08:56
I'm closing this issue. If it is still a problem, please provide more information.

**Closed as completed by mlichvar** 2020-08-12 08:56 UTC
